config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     login GET    /login(.:format)                                                                         sessions#new
#                           POST   /login(.:format)                                                                         sessions#create
#                    logout DELETE /logout(.:format)                                                                        sessions#destroy
#               admin_users GET    /admin/users(.:format)                                                                   admin/users#index
#                           POST   /admin/users(.:format)                                                                   admin/users#create
#            new_admin_user GET    /admin/users/new(.:format)                                                               admin/users#new
#           edit_admin_user GET    /admin/users/:id/edit(.:format)                                                          admin/users#edit
#                admin_user GET    /admin/users/:id(.:format)                                                               admin/users#show
#                           PATCH  /admin/users/:id(.:format)                                                               admin/users#update
#                           PUT    /admin/users/:id(.:format)                                                               admin/users#update
#                           DELETE /admin/users/:id(.:format)                                                               admin/users#destroy
#                      root GET    /                                                                                        tasks#index
#          confirm_new_task POST   /tasks/new/confirm(.:format)                                                             tasks#confirm_new
#                     tasks GET    /tasks(.:format)                                                                         tasks#index
#                           POST   /tasks(.:format)                                                                         tasks#create
#                  new_task GET    /tasks/new(.:format)                                                                     tasks#new
#                 edit_task GET    /tasks/:id/edit(.:format)                                                                tasks#edit
#                      task GET    /tasks/:id(.:format)                                                                     tasks#show
#                           PATCH  /tasks/:id(.:format)                                                                     tasks#update
#                           PUT    /tasks/:id(.:format)                                                                     tasks#update
#                           DELETE /tasks/:id(.:format)                                                                     tasks#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  namespace :admin do
    resources :users
  end

  root to: 'tasks#index'
  resources :tasks do
    post :confirm, action: :confirm_new, on: :new
    post :import, on: :collection
  end
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :bigint           not null, primary key
#  name        :string(30)       not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#

class Task < ApplicationRecord
  validates :name, presence: true
  validates :name, length: {maximum: 30}
  validate :validate_name_not_including_comma

  # デフォルトのソート順指定
  scope :record_entity_expansion, -> {order(created_at: :desc)}

  belongs_to :user
  has_one_attached :image

  def self.csv_attributes
    return ["name", "description", "created_at", "updated_at"]
  end

  def self.generate_csv
    CSV.generate(headers: true) do |csv|
      csv << csv_attributes
      all.each do |task|
        csv << csv_attributes.map{|attr| task.send(attr)}
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      task = new
      task.attributes = row.to_hash.slice(*csv_attributes)
      task.save!
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[name created_at]
  end
  def self.ransackable_associations(auth_object = nil)
    []
  end

end

private

def validate_name_not_including_comma
  errors.add(:name, 'にカンマを含めることはできません') if name&.include?(',')
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @q = current_user.tasks.ransack(params[:q])
    @tasks = @q.result(distinct: true).page(params[:page])

    respond_to do |format|
      format.html
      format.csv {send_data @tasks.generate_csv, filename: "tasks-#{Time.zone.now.strftime('%Y%m%S')}.csv"}
    end
  end

  def show
  end

  def new
    @task = Task.new
  end

  def confirm_new
    @task = current_user.tasks.new(task_params)
    render :new unless @task.valid?
  end

  def edit
  end

  def create
    @task = Task.new(task_params.merge(user_id: current_user.id))

    if params[:back].present?
      render :new
      return
    end

    if @task.save
      # メールを送信する
      #TaskMailer.creation_email(@task).deliver_now
      #SampleJob.perform_later
      redirect_to @task, notice: "タスク「#{@task.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    @task.update!(task_params)
    redirect_to tasks_url, notice: "タスク「#{@task.name}」を更新しました。"
  end

  def destroy
    @task.destroy
  end

  def import
    current_user.tasks.import(params[:file])
    redirect_to tasks_url, notice: "タスクを追加しました。"
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :image)
  end

  def set_task
    @task = current_user.tasks.find(params[:id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.slim
- if task.errors.present?
  ul#error_explanation
    - task.errors.full_messages.each do |message|
      li = message

= form_with model: task, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'task-name'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'task-description'
  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control', id: 'task-image'
  = f.submit nil, class: 'btn btn-primary'

app/views/tasks/confirm_new.html.slim
h1 登録内容の確認

= form_with model: @task, local: true do |f|
  table.table.table-hover
    tbody
      tr
        th = Task.human_attribute_name(:name)
        td = @task.name
        = f.hidden_field :name
      tr
        th = Task.human_attribute_name(:description)
        td = raw Rinku.auto_link(simple_format(@task.description), :all, 'target="_blank"')
        = f.hidden_field :description
  = f.submit '戻る', name: 'back', class: 'btn btn-secondary mr-3'
  = f.submit '登録', class: 'btn btn-danger'

app/views/tasks/destroy.js.erb
document.querySelector("#task-<%= @task.id %>").style.display = 'none';

var message = document.createElement('p');
message.innerText = 'タスク「<%= @task.name %>」を削除しました。残りのタスクは<%= Task.count %>件です。';
document.querySelector('table').insertAdjacentElement('beforebegin', message);

app/views/tasks/edit.html.slim
h1 タスクの編集

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: { task: @task }

app/views/tasks/index.html.slim
h1 タスク一覧

= search_form_for @q, class: 'md-5' do |f|
  .form-group.row
    = f.label :name_cont, '名称', class: 'col-sm-2 col-form-label'
    .col-sm-10
      =f.search_field :name_cont, class: 'form-control'
  .form-group.row
    = f.label :created_at_gteq, '登録日時', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :created_at_gteq, class: 'form-control'
  .form-group
    = f.submit class: 'btn btn-outline-primary'

= link_to '新規登録', new_task_path, class: 'btn btn-primary mb-3'

.mb-3
  = paginate @tasks
  = page_entries_info @tasks

table.table.table-hover
  thead.thread-default
    tr
      th = sort_link(@q, :name, [:name, 'created_at desc'])
      th = Task.human_attribute_name(:created_at)
      th
    tbody
      - @tasks.each do |task|
        tr id="task-#{task.id}"
          td = link_to task.name, task
          td = task.created_at
          td
            = link_to '編集', edit_task_path(task), class: 'btn btn-primary mr-3'
            = link_to '削除', task, method: :delete, remote: true, data: {confirm:"タスク「#{task.name}」を削除します。よろしいですか？"},
                    class: 'btn btn-danger delete'
= link_to 'エクスポート', tasks_path(format: :csv), class: 'btn btn-primary mr-3'
= form_tag import_tasks_path, multipart: true, class: 'mb-3' do
    = file_field_tag :file
    = submit_tag "インポート", class: 'btn btn-primary'

app/views/tasks/new.html.slim
h1 タスクの新規登録

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: { task: @task }

app/views/tasks/show.html.slim
h1 タスクの詳細

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th = Task.human_attribute_name(:id)
      td = @task.id
    tr
      th = Task.human_attribute_name(:name)
      td = @task.name
    tr
      th = Task.human_attribute_name(:description)
      td = raw Rinku.auto_link(simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div"), :all, 'target="_blank"')
    tr
      th = Task.human_attribute_name(:image)
      td = image_tag @task.image if @task.image.attached?
    tr
      th = Task.human_attribute_name(:created_at)
      td = @task.created_at
    tr
      th = Task.human_attribute_name(:updated_at)
      td = @task.updated_at

= link_to '編集', edit_task_path, class: 'btn btn-primary mr-3'
= link_to '削除', @task, method: :delete, data: {confirm:"タスク「#{@task.name}」を削除します。よろしいですか？"},  class: 'btn btn-danger'